#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SermonCasting.Resource", IsApplication=true)]

namespace SermonCasting
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040002
			public const int background = 2130968578;
			
			// aapt resource value: 0x7f040009
			public const int black = 2130968585;
			
			// aapt resource value: 0x7f040004
			public const int bluedark = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int bluelight = 2130968579;
			
			// aapt resource value: 0x7f040006
			public const int greendark = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int greenlight = 2130968581;
			
			// aapt resource value: 0x7f040001
			public const int grey = 2130968577;
			
			// aapt resource value: 0x7f040008
			public const int orangedark = 2130968584;
			
			// aapt resource value: 0x7f040007
			public const int orangelight = 2130968583;
			
			// aapt resource value: 0x7f040000
			public const int white = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int adbackground = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int adicon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int settings30x60 = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07001b
			public const int ASV = 2131165211;
			
			// aapt resource value: 0x7f070001
			public const int Churches = 2131165185;
			
			// aapt resource value: 0x7f070008
			public const int ControlLayout = 2131165192;
			
			// aapt resource value: 0x7f070007
			public const int Controls = 2131165191;
			
			// aapt resource value: 0x7f07001c
			public const int ESV = 2131165212;
			
			// aapt resource value: 0x7f070003
			public const int Icon = 2131165187;
			
			// aapt resource value: 0x7f07001e
			public const int KJV = 2131165214;
			
			// aapt resource value: 0x7f070000
			public const int Main = 2131165184;
			
			// aapt resource value: 0x7f07001d
			public const int NIV = 2131165213;
			
			// aapt resource value: 0x7f07000e
			public const int Slider = 2131165198;
			
			// aapt resource value: 0x7f070002
			public const int TitleBar = 2131165186;
			
			// aapt resource value: 0x7f07001f
			public const int YLT = 2131165215;
			
			// aapt resource value: 0x7f07000d
			public const int churchButton = 2131165197;
			
			// aapt resource value: 0x7f070006
			public const int churchList = 2131165190;
			
			// aapt resource value: 0x7f07000f
			public const int currentText = 2131165199;
			
			// aapt resource value: 0x7f070011
			public const int durationText = 2131165201;
			
			// aapt resource value: 0x7f07000b
			public const int frameLayout1 = 2131165195;
			
			// aapt resource value: 0x7f070010
			public const int frameLayout2 = 2131165200;
			
			// aapt resource value: 0x7f070017
			public const int horizontalScrollView1 = 2131165207;
			
			// aapt resource value: 0x7f070014
			public const int layoutList = 2131165204;
			
			// aapt resource value: 0x7f070016
			public const int layoutWeb = 2131165206;
			
			// aapt resource value: 0x7f070018
			public const int linearTabs = 2131165208;
			
			// aapt resource value: 0x7f07001a
			public const int passageButton1 = 2131165210;
			
			// aapt resource value: 0x7f070009
			public const int playButton = 2131165193;
			
			// aapt resource value: 0x7f070015
			public const int playList = 2131165205;
			
			// aapt resource value: 0x7f070012
			public const int seekBar = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int selectedText = 2131165203;
			
			// aapt resource value: 0x7f070005
			public const int settingsButton = 2131165189;
			
			// aapt resource value: 0x7f07000a
			public const int stopButton = 2131165194;
			
			// aapt resource value: 0x7f070004
			public const int titleText = 2131165188;
			
			// aapt resource value: 0x7f07000c
			public const int versionText = 2131165196;
			
			// aapt resource value: 0x7f070019
			public const int webView1 = 2131165209;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int menu = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050008
			public const int ApplicationName = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int AutoPlay = 2131034119;
			
			// aapt resource value: 0x7f05000b
			public const int Back = 2131034123;
			
			// aapt resource value: 0x7f05000a
			public const int Church = 2131034122;
			
			// aapt resource value: 0x7f050005
			public const int DropDown = 2131034117;
			
			// aapt resource value: 0x7f050009
			public const int From = 2131034121;
			
			// aapt resource value: 0x7f050000
			public const int Loading = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int Loading2 = 2131034113;
			
			// aapt resource value: 0x7f05000c
			public const int Passage1 = 2131034124;
			
			// aapt resource value: 0x7f050003
			public const int Pause = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int Play = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int Stop = 2131034116;
			
			// aapt resource value: 0x7f05000d
			public const int Temp = 2131034125;
			
			// aapt resource value: 0x7f050006
			public const int Versions = 2131034118;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
